### ISSUE TITLE
Ability to pause and resume timers inside the benchmark block

### ISSUE THREAD

**Issue by denizevrenci** [martinus/nanobench#35] opened 2020-06-22 06:24 UTC
It would be nice to have a facility similar to Google Benchmark's `PauseTiming()` and `ResumeTiming()` for benchmarks that need a setup phase at each iteration.

**Comment by martinus** [comment] 2020-06-23 11:24
That would only work reliably with very slow benchmark, and is complicated by the performance counters. Duplicate of #22

**Closed by martinus** 2020-06-23 11:24 UTC

**Comment by martinus** [comment] 2023-02-16 19:35
See #86
